name: New Tag generator

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Fetch tags
        run: git fetch --tags --prune

      - name: Mayor release
        if: contains(github.event.pull_request.labels.*.name, 'mayor update')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          current_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "Current tag: $current_tag"
          echo "Mayor update"
          new_tag=$(echo "$current_tag" | awk -F. -v OFS=. '{print $1,$2+1,0}')
          echo "New tag: $new_tag"
          git tag $new_tag
          git push origin $new_tag

      - name: Minor release
        if: contains(github.event.pull_request.labels.*.name, 'mayor update') == false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          current_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "Current tag: $current_tag"
          echo "Minor update"
          new_tag=$(echo "$current_tag" | awk -F. '{$NF = $NF + 1;} 1' OFS=.)
          echo "New tag: $new_tag"
          git tag $new_tag
          git push origin $new_tag

